### ISSUE TITLE
Task-1 A warm up task

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/GeekHaven-Community-App#1]
Add your Name and Github_username in [contibutors.xml](https://github.com/opencodeiiita/GeekHaven-Community-App/blob/master/app/src/main/res/values/contributors.xml) located in res/values folder.

**PS: This issue is open for all, so no need to claim this issue. You can directly create a pull request**

_Happy Contributing!😊_

**Comment by muffinboy19** [comment]
The issue is now over
