### ISSUE TITLE
"The One And Only."

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#104]
GitHub Issue: Add SHA-1 and SHA-256 Keys for Google Login in Firebase Console 🚀

🛠 Task Description:

Firebase Console Configuration:
🔄 Add the SHA-1 key and SHA-256 key to the Firebase Console to enable Google login features in the app.
🌐 Navigate to the Firebase project settings and locate the section for adding SHA keys.
🔐 Input both the SHA-1 and SHA-256 keys securely.
Note: If you are not registered in the Firebase Console, please DM your email ID in the GitHub comments or on Discord.

🎉 Happy Contributing! Your contribution in enhancing authentication features is greatly appreciated. 🌟

for this issue you have provide your email id and then make a blank pr only those who are added in the conosle will get there pr merged

**Comment by MonuGit9** [comment]
Claim

**Comment by MonuGit9** [comment]
Plz add me
monusinghbharadwaj@gmail.com

**Comment by sarthakvermaa** [comment]
claim

**Comment by muffinboy19** [comment]
done

**Comment by kushal7201** [comment]
@muffinboy19  Plz add this email:
10kushalbansal.kb@gmail.com

**Comment by Mannxxx** [comment]
Plz add me
mansi21021@gmail.com

**Comment by MonuGit9** [comment]
Claim

**Comment by rnavaneeth992** [comment]
> GitHub Issue: Add SHA-1 and SHA-256 Keys for Google Login in Firebase Console 🚀
> 
> 🛠 Task Description:
> 
> Firebase Console Configuration: 🔄 Add the SHA-1 key and SHA-256 key to the Firebase Console to enable Google login features in the app. 🌐 Navigate to the Firebase project settings and locate the section for adding SHA keys. 🔐 Input both the SHA-1 and SHA-256 keys securely. Note: If you are not registered in the Firebase Console, please DM your email ID in the GitHub comments or on Discord.
> 
> 🎉 Happy Contributing! Your contribution in enhancing authentication features is greatly appreciated. 🌟
> 
> for this issue you have provide your email id and then make a blank pr only those who are added in the conosle will get there pr merged

@muffinboy19 r.navaneeth992@gmail.com
