### ISSUE TITLE
is the Splash Screen wrong ..? 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#109]
### Description:
The current splash screen needs a redesign, and we want to replace the existing logo with the GeekHaven logo in all-white. Here's the proposed design:

### Deadline:
complete the task in 2 days 
ask for the geekhaven logo if you dont have it 

Happy coding! 🖥️🎉
---
![spoohs](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/dd2489b2-d658-4276-89ad-12d80ffc47de)

**Comment by sarthakvermaa** [comment]
claim

**Comment by MonuGit9** [comment]
Claim

**Comment by CodinJack** [comment]
claim

**Comment by k7aditya** [comment]
claim

**Comment by CodinJack** [comment]
Where is the current splash screen? like where do i make the changes that im supposed to do?

**Comment by muffinboy19** [comment]
there is a activity called splash sccreen
