### ISSUE TITLE
Take My Intro if you can.... 💢 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#110]
### Description:
- The task involves redesigning three intro screens, discarding the previous ones.
- Follow the design specified in the Figma file to ensure a seamless flow between screens. 🔄
- Make sure  the  blue button at the bottom with the correct shape and functionality across all three screens. 🤖🔵

### Deadline:
- Complete the task within 2 days.

### Happy coding! 🖥️🎉
---

1 . 
![sd](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/177bdf27-3e3e-42ea-827b-7f8976fbf304)

2.
![ds](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/eec93f6a-aad9-4977-8fa7-f0983c630197)

3.
![dd](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/f0b1e11c-600b-4533-8d96-1048db455ac9)

**Comment by criticic** [comment]
claim

**Comment by MonuGit9** [comment]
Claim
