### ISSUE TITLE
Can you sign me in ...pls 😄 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#111]
### Description:
- The new task requires designing a fresh sign-in screen, replacing the existing one.
- Additionally, create a sign-up screen according to the provided design guidelines.

### Deadline:
- Complete the task within 2 days.
- If you need any design assets or specifications, please request them.

Disclaimer : to work on this issue you shoould be added in the firebase console 
### Happy designing! 🎨🖥️
---
1. 
![qq](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/06d9946f-abd9-44af-910d-072287d8d581)

2.
![bb](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/ba37ce73-8c5c-4d24-bd52-699faf1bf7da)

**Comment by CodinJack** [comment]
claim

**Comment by MonuGit9** [comment]
Claim

**Comment by Mannxxx** [comment]
Claim
