### ISSUE TITLE
can you bottom nav bar me .. 🥵 //>><>

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#112]
### Description:
- Your new task involves changing the current bottom navigation bar to match the given design.
- Ensure that the updated design aligns with the provided specifications.
- also make new screens for it delete the prevous one 
- each button should be working 

### Deadline:
- Complete the task within 2 days.
- If additional details or design assets are required, please request them.

### Happy coding! 🖥️🎨
---
![aa](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/56511e18-ee47-4b75-a556-c99f1bdb3fa3)

**Comment by criticic** [comment]
claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by MonuGit9** [comment]
Claim

**Comment by Mannxxx** [comment]
Claim
