### ISSUE TITLE
is the profile page correct 👨‍🏫 <>?

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#113]
### Description:
- Your new task involves designing a fresh XML layout for the profile page.
- Create the XML in a way that it can be seamlessly added to the exact location when needed in the application.
- make sure the screen is scrollable 

### Deadline:
- Complete the task within 2 days.
- If there are specific design guidelines or assets required, please request them.

### Happy designing! 🖌️📱
---
![aa](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/b23f9861-8e6c-4bdd-abea-b796dacb9235)

**Comment by sarthakvermaa** [comment]
claim

**Comment by MonuGit9** [comment]
Claim

**Comment by adv8j** [comment]
Claim

**Comment by Mannxxx** [comment]
Claim
