### ISSUE TITLE
Citizen Kane (1941) Film Drama

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#116]
Certainly! Here's the updated description in Markdown:

---

🎨 **Home Screen Design and Firestore Integration:**

1. 🖼️ **Bottom Navigation Bar Design:**
   - If the bottom navigation bar design is already in place, great! If not, leave it as is.
   - Ensure that the home page design adheres to the specified guidelines.

2. 📋 **Task Collection in Firestore:**
   - Create a collection named "Task" in Firestore to store project-related data.
   - Populate the "Task" collection with dummy data representing ongoing projects.
   - Display the ongoing projects on the home page.
   - Keep the "Projects" bar static for now; no need to change its behavior.

3. 📋 **myTask Collection in Firestore:**
   - Create a collection named "myTask" in Firestore to store personalized project data.
   - Populate the "myTask" collection with dummy data for individual projects.
   - Display the "my projects" section on the home page.

   **Note:** Ensure that the design is visually appealing and that the integration with Firestore is seamless. Dummy data should be representative of real-world scenarios to showcase the functionality effectively.

---
![aa](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/8d817f7e-b6dd-487e-ab70-99883e3ef618)

**Comment by DikshantK2004** [comment]
Claim

**Comment by criticic** [comment]
claim

**Comment by Mannxxx** [comment]
Claim
