### ISSUE TITLE
 In the Mood for Love (2000) 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#118]
---

🎨 **Designing and Implementing Project Page:**

1. 📐 **Project Page Design:**
   - Design the project page, incorporating elements such as project cards, progress bars, and profile icons.
   - Fetch and display projects from the existing collection where all projects are stored.
   - Keep the progress bar and profile icons static for now; functionality enhancements will be addressed in future tasks.

2. ➕ **New Project Creation Page:**
   - Modify the design of the new page that opens when the "+" button is clicked to create a new project.
   - Include sections for project name, description, labels, and a GitHub link.
   - Ensure a clear and user-friendly layout for adding project details.

   **Note:** Registration on the console is required for working on this issue, and make sure the design aligns with the overall app aesthetic.

---
1.
![aa](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/5b66f667-6d0f-489c-a0a9-52832d6a5bf9)

2.
![aa](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/80239382-bd12-4b0a-bab3-3374643c0013)

**Comment by criticic** [comment]
claim

**Comment by Mannxxx** [comment]
Claim
