### ISSUE TITLE
 There Will Be Blood (2007) 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#119]
---

🗓️ **Designing a Calendar Page:**

**Description for the Design:**

1. 📅 **Current Date and Month Display:**
   - Create the first `TextView` to display the current date and month along with a random emoji.

2. 📆 **Number of Tasks for Today:**
   - Display the number of tasks for today in a separate section. For now, keep it dummy data.

3. 📅 **Weekly Calendar Implementation:**
   - Refer to the tutorial link [here](https://www.youtube.com/watch?v=knpSbtbPz3o) to implement a weekly calendar.
   - Include switching tabs for months, weeks, etc., similar to the example in the video.

4. 🔄 **Calendar Button Functionality:**
   - Design a button to show/hide the calendar view.
   - When pressed, the calendar should become visible, and the button color should change accordingly.
   - When unpressed, the calendar should become invisible, and the button color should revert.

**Disclaimer:**
   - Refer to the Figma file for a better understanding of the desired design.

**Note:** Ensure that the calendar page aligns with the specified design and functionality as described in the Figma file.
since this is a big task more points will be awareded if the sent output matches the desgin and discritption and deadline is of 3 days 

---
![aa](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/573c95e5-cb25-4405-bd10-d5de03264ffc)

**Comment by parth1egend** [comment]
Claim

**Comment by Mannxxx** [comment]
Claim

**Comment by insanecoder02** [comment]
@Mannxxx make ur PR by EOD otherwise it will be assigned to someone else.

**Comment by criticic** [comment]
Claim

**Comment by Mannxxx** [comment]
![image](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/107349957/d313ec91-ee3c-4b82-8362-9a460c84d886)


@insanecoder02, Will this design work? I am still working on this, I can further improve the design.

**Comment by insanecoder02** [comment]
@Mannxxx the design u provided doesn't match with the given reference. You have to make it exactly like that

**Comment by Apoorv012** [comment]
claim

**Comment by muffinboy19** [comment]
claim now

**Comment by Apoorv012** [comment]
Claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by insanecoder02** [comment]
@criticic plz send your PR asap.
