### ISSUE TITLE
Repair Email Authentication System

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#130]
- **Issue Description:** 🛠️ Fix the current authentication system, specifically addressing the issue preventing users from successfully logging in using email authentication.

- **Task Details:**
   - Investigate and identify the root cause of the email authentication failure.
   - Rectify any errors or misconfigurations in the authentication system.
   - Ensure that users can seamlessly log in using their email credentials.
   - Conduct thorough testing to confirm the resolution of the email authentication issue.

**Comment by MonuGit9** [comment]
Claim

**Comment by Apoorv012** [comment]
claim
