### ISSUE TITLE
project page enhancemnt 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#133]
#### 1. Merge and Rename Database Collections
- **Issue Description:** 🔄 Streamline project data management by merging and renaming database collections.
- **Task Details:**
   - Combine the data from the "tasks" and "Task" collections into a single collection named "project."
   - Update the code fetching data to accommodate the merged collection.
   - Ensure consistency in dummy data representation after the merging process.

#### 2. Separate Favourite Projects
- **Issue Description:** ⭐ Implement a feature to distinguish and display favourite projects separately.
- **Task Details:**
   - Introduce a mechanism to mark projects as favourites.
   - Create a UI element (e.g., a button) to toggle between viewing all projects and viewing only favourite projects.
   - Modify the UI to visually indicate the current view (all or favourites) based on the user's selection.

#### 3. Update UI for Favourites Button
- **Issue Description:** 🎨 Improve the visual representation of the Favourites button on the Project page.
- **Task Details:**
   - Enhance the UI of the Favourites button to reflect the current state (all or favourites).
   - Implement changes according to the design specifications to improve user experience.

#### 4. Make Project Fragment Scrollable
- **Issue Description:** 🔄 Ensure a better user experience by enabling scroll functionality in the Project fragment.
- **Task Details:**
   - Modify the Project fragment to make it scrollable.
   - Ensure that users can easily navigate through the project list, especially if the list exceeds the screen height.

**Comment by criticic** [comment]
claim

**Comment by MonuGit9** [comment]
Claim

**Comment by kushal7201** [comment]
Claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by Mannxxx** [comment]
claim

**Comment by muffinboy19** [comment]
@sarthakvermaa  if you dont make a pr till 11:25 pm then you will be reassined for this issue

**Comment by criticic** [comment]
claim
