### ISSUE TITLE
redesing the communit screen

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#134]
#### 1. Redesign Community Fragment
- **Issue Description:** 🎨 Enhance the visual appeal and functionality of the Community fragment based on the provided design.
- **Task Details:**
   - Implement a scrollable design for the Community fragment.
   - Align the layout and elements according to the given design specifications.
   - Ensure a consistent and visually appealing representation of community-related information.
   - Test the scroll functionality to guarantee a seamless user experience.

#### 2. Refine Profile Page Design
- **Issue Description:** 🔄 Improve the design consistency of the Profile page and add necessary spacing for aesthetics.
- **Task Details:**
   - Adjust the Profile page layout to match the overall design theme more closely.
   - Introduce spacing adjustments to enhance the visual appeal.
   - Confirm that the Profile page design aligns with the provided design specifications.
   - Implement any necessary changes to create a more cohesive and polished look.

---
![aa](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/4ccdac9a-fab6-4c34-9903-97a5bcec90b9)

**Comment by sarthakvermaa** [comment]
claim

**Comment by MonuGit9** [comment]
claim
