### ISSUE TITLE
signup -sign in Google

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#136]
#### Add Authentication to Signup and Signin Screens

- **Issue Description:** 🔐 Enhance user security by implementing authentication features on both the signup and signin screens.
- **Task Details:**
   - **Signup Screen:**
     - Integrate authentication for email signup.
     - Implement Google Sign-In functionality for users who prefer signing up with their Google account.
     - Ensure proper validation and error handling for the signup process.

   - **Signin Screen:**
     - Enable authentication for email signin.
     - Implement Google Sign-In functionality for users who prefer signing in with their Google account.
     - Ensure proper validation and error handling for the signin process.

**Comment by criticic** [comment]
claim

**Comment by kushal7201** [comment]
Claim
