### ISSUE TITLE
Add function to the New project Screen 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#137]
#### Implement Functionality for "Add New Project" Screen

- **Issue Description:** 🚀 Enhance the app's functionality by implementing features for adding a new project and displaying it on the home screen.
- **Task Details:**
   - **Add New Project Screen:**
     - Design and implement the "Add New Project" screen with the necessary input fields and UI elements.
     - Include functionalities such as adding project details, attaching files, setting deadlines, etc., based on the provided design.
     - Implement validation to ensure that all required fields are filled appropriately.
     - Add functionality to save the new project data to the database.

   - **Home Screen:**
     - After successfully adding a new project, update the home screen to display the newly added project.
     - Implement the logic to fetch and display the list of projects, including the newly added one.
     - Ensure that the new project is seamlessly integrated into the existing project list on the home screen.

**Comment by kushal7201** [comment]
Claim

**Comment by Mannxxx** [comment]
claim

**Comment by insanecoder02** [comment]
@kushal7201 plz send your PR asap.

**Comment by kushal7201** [comment]
@insanecoder02  I'm working on it and will send the PR as soon as its done

**Comment by criticic** [comment]
claim
