### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#138]
#### Implement Search Functionality and Pop-Up Menu in Project Page

- **Issue Description:** 🔍👥 Enhance user navigation on the Project page by adding search functionality and a pop-up menu.
- **Task Details:**
   - **Search Functionality:**
     - Integrate a search bar or input field on the Project page to enable users to search for specific projects.
     - Implement logic to filter and display projects based on user input.
     - Ensure a smooth and responsive search experience for users.

   - **Pop-Up Menu:**
     - Design and implement a pop-up menu on the Project page, accessible through a designated button or gesture.
     - Include options in the pop-up menu, such as sorting projects, applying filters, or accessing additional actions.
     - Ensure that the pop-up menu aligns with the provided design and enhances user interaction.

---
![aa](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/4686c7a4-2457-4e82-8188-64537d06288b)

**Comment by kushal7201** [comment]
Claim

**Comment by criticic** [comment]
claim
