### ISSUE TITLE
Sagnik Mandal

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#143]
#### Create Project Details Page

- **Issue Description:** 📑 Develop a new page that opens when a project is clicked on the horizontal scroll view in the home screen. This page should display the project description and all the tasks associated with the project.
- **Task Details:**
   - Design and implement a new page that presents comprehensive project details, including the project description and a list of tasks.
   - If no tasks are currently allotted to the project, clearly communicate this in the interface.
   - Implement a feature that checks whether the user is authorized to view the project. If the user is not part of the project, display a message indicating that they are not authorized to view project details.
   - Ensure the UI is user-friendly, providing a seamless experience for users exploring project details.
---
![aa](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/22a8516a-4b4d-442f-9289-243515d97e30)

**Comment by criticic** [comment]
claim
