### ISSUE TITLE
Dikshant Khandelwal

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#144]
#### Implement Chat Feature in Community Page

- **Issue Description:** 💬 Enhance user interaction by adding a chat feature to the Community page. Utilize a new method allowing the implementation of both one-on-one and group chat functionalities.
- **Task Details:**
   - Investigate and explore the provided link to discover a new method for implementing chat features in the app.
   - Design and implement the chat feature specifically on the Community page.
   - Allow users to engage in both one-on-one and group chats.
   - Ensure the chat functionality aligns with the overall theme and design principles of the application.
   - Thoroughly test the chat feature to guarantee a seamless and secure communication experience.
   - https://www.youtube.com/watch?v=GrAwH6Sb834&t=166s

**Comment by DikshantK2004** [comment]
claim

**Comment by criticic** [comment]
claim

**Comment by Apoorv012** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by muffinboy19** [comment]
i am really sorry i forgot to commmnet 😩

**Comment by criticic** [comment]
claim

**Comment by muffinboy19** [comment]
lets  do 9:40

**Comment by criticic** [comment]
claim

**Comment by muffinboy19** [comment]
claim now

**Comment by criticic** [comment]
claim
