### ISSUE TITLE
Task-2 Logo For the App

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#2]
**Design a Good Logo for the App** 🎨

This issue is **Competitive**, which means the **best logo** would be selected and then **awarded with points** 🏆.

While creating a **PR**, **attach your logo in the PR itself** 📎. Take **inspiration from the GeekHaven logo** and **include it in the design**.

**Note: This issue will be active for 3 days.** ⏳

Logo is available in the below **drive link**:
[Drive Link](https://drive.google.com/drive/folders/1j45dI9Zmm1eQkDE7TUzrQXP1vrBJKZ0U) 🌐

*Happy contributing!* 😊

**Comment by kushal7201** [comment]
I want to claim the issue @muffinboy19

**Comment by muffinboy19** [comment]
This issue is tagged everyone which means you dont need to claim it , just make a pr for this issue and the best of all pr would be merged @kushal7201
