### ISSUE TITLE
Make a homeActivity 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#4]
**Create HomeActivity with Bottom Navigation Bar** 🏡

Your task for this issue is to design a **HomeActivity** featuring a **bottom navigation bar** with **four fragments**:

1. **Feed**
2. **Community**
3. **Project**
4. **Profile**

Additionally, ensure to create four corresponding fragments. Feel free to leave the fragment content blank for now. 📝

*Happy contributing!* 😊

**Comment by Aryan4884** [comment]
claim

**Comment by prakhar-py** [comment]
claim

**Comment by muffinboy19** [comment]
issue is compeleted by @tonyStark-Jr
