### ISSUE TITLE
create a xml for profile fragment 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#81]
#### Design Inspiration From the below drive link 
Image named Profile_fragment
(https://drive.google.com/drive/folders/1j45dI9Zmm1eQkDE7TUzrQXP1vrBJKZ0U)

#### Tasks
1. Create a new XML layout file in the `res/layout` directory.
2. Add an `ImageView` for the profile image.
3. Add a `TextView` for displaying the name.
4. Add a `TabLayout` in the fragment with 3 fragments.

#### Deadline
⏰ **2 days from claim date**

---

**Happy Contributing!** 🎉

**Comment by kushal7201** [comment]
claim

**Comment by CodinJack** [comment]
claim

**Comment by muffinboy19** [comment]
Assigned to @kushal7201

**Comment by insanecoder02** [comment]
assigned to @CodinJack .
As @kushal7201 has already assigned with 3 tasks

**Comment by muffinboy19** [comment]
@CodinJack  you have 5 hours left to compelet this task

**Comment by CodinJack** [comment]
@muffinboy19 im facing difficulties in making the xml file, kindly unassign me the task :(

**Comment by Apoorv012** [comment]
claim

**Comment by muffinboy19** [comment]
done finally
