### ISSUE TITLE
Add Hamburger Drawer  

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#82]
#### Tasks
1. Create a hamburger drawer In the ``MainActivity`` that includes the profile image.
2. Add four options in the drawer named Option 1, Option 2, Option 3, and Option 4 for now .

#### Notes
- Customize the drawer's appearance and behavior based on the design inspiration from the drive link .
- Ensure smooth navigation and a user-friendly experience.

#### Drive Link 
https://drive.google.com/drive/folders/1j45dI9Zmm1eQkDE7TUzrQXP1vrBJKZ0U
#### Deadline
⏰ **2 days from claim date**

---

**Happy Contributing!** 🎉

**Comment by ParadoxNJ005** [comment]
Sir , I want to work on this issue

**Comment by muffinboy19** [comment]
done
