### ISSUE TITLE
Create a LoginActivity 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#83]
#### Design Inspiration
From the Tumblr App 

#### Tasks
1. Develop a `LoginActivity` that prompts the user for their username/email.
2. Display the logo on the login screen.

#### Notes
- Implement a clean and user-friendly interface.
- Ensure proper handling of user input.

#### Deadline
⏰ **2 days from claim date**

---

**Happy Contributing!** 🎉

**Comment by chiragmalik2612** [comment]
claim

**Comment by muffinboy19** [comment]
@chiragmalik2612   in this issue you too have to create  a new activity , do you still wana claim it

**Comment by chiragmalik2612** [comment]
@muffinboy19  i don't know what does it exactly mean or how to do this "  create a new activity". can you please tell me what is this all about.

**Comment by muffinboy19** [comment]
It is a task of android development , are you help with android development creating activites , which involve , kotllin n xml

**Comment by chiragmalik2612** [comment]
No as of now I'm not aware of android dev.

**Comment by CodinJack** [comment]
claim

**Comment by prakhar-py** [comment]
claim

**Comment by muffinboy19** [comment]
assigned to @tonyStark-Jr

**Comment by muffinboy19** [comment]
@tonyStark-Jr  your deadline is near to complete this task

**Comment by Apoorv012** [comment]
claim

**Comment by keshavkhetan123** [comment]
claim

**Comment by Aastha-ojha-20** [comment]
claim

**Comment by muffinboy19** [comment]
this issue is closed as the  project login screen would be implemented in a different time
