### ISSUE TITLE
Change the BottomNavBar

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#88]
you have to change the bottom nav bar as such when the icon is selected white colour should be used 
and when not #717E8E  should be used

**Comment by aashray374** [comment]
sir I want to claim this task

**Comment by Apoorv012** [comment]
claim

**Comment by Aastha-ojha-20** [comment]
claim

**Comment by muffinboy19** [comment]
@aashray374  assigned to you
