### ISSUE TITLE
Add a Custom TabLayout 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#89]
You have to add a custom tab layout like in the photo attached below 

here it will switch between Activity and Messages just like the picture

ps: Also make the entire desgin on xml for this task

![d7c4ce8e-dc33-4257-9337-355606a91cf7](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/e9cca364-4689-4748-beab-fe5a43798266)

**Comment by ParadoxNJ005** [comment]
Sir i want to do this task .

**Comment by muffinboy19** [comment]
@ParadoxNJ005  you can register first

**Comment by muffinboy19** [comment]
you can start working now @ParadoxNJ005
