### ISSUE TITLE
Enter Your email...

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#90]
Create 2 xml page looking exactly like the desgin given below 
xml -1 
![69a48fe6-3bb7-409a-929c-6769c85e1c90](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/3d03de7c-5e41-4cf6-acaa-c4f395306762)

xml -2
![0c8255cd-c6ad-4d40-987e-79f0338062ca](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/7a7f4262-2142-4ead-92e0-88acef9c157a)

**Comment by aashray374** [comment]
Sir I want to claim this task

**Comment by muffinboy19** [comment]
Assigned to @aashray374

**Comment by muffinboy19** [comment]
reminder @aashray374
