### ISSUE TITLE
Repair Profile Fragment Design

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#96]
#### **Description:**

The current profile fragment does not match the desgin your task is to fix that 

#### **Deadline:**

Your deadline for this task is 2 days. 

**Note:** Your design touch will bring a fresh look to our user profiles! 😄

---
![thnag](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/f6075eac-2d8d-49d0-b5e3-e7260e881abb)

**Comment by criticic** [comment]
claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by ParadoxNJ005** [comment]
claim

**Comment by Apoorv012** [comment]
claim

**Comment by MonuGit9** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by insanecoder02** [comment]
@ParadoxNJ005 your deadline is near

**Comment by Apoorv012** [comment]
claim
