### ISSUE TITLE
Fix Me please!!! 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#97]
### GitHub Issue: Bug Fixes 🐞

**1. Remove Toolbar:**
   - Issue: Toolbar persists in the app.
   - Action: Remove the toolbar from the app.

**2. Chat Fragment Visibility:**
   - Issue: Chat fragment is visible on app launch, despite not being selected.
   - Action: Ensure the chat fragment is hidden initially; fix visibility issue.

**3. Hamburger Swipe Accessibility:**
   - Issue: Hamburger menu not accessible with swipe feature.
   - Action: Implement swipe feature for hamburger menu accessibility.

**Happy Contributing!** 🚀

**Comment by DikshantK2004** [comment]
Claim

**Comment by Apoorv012** [comment]
claim

**Comment by MonuGit9** [comment]
claim
