### ISSUE TITLE
Give your Intro

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#98]
### GitHub Issue: Introduce Intro Screens 🌟

**1. Intro1 Screen:**
   - Task: Create the Intro1 screen to display introductory data.
   - Design: Reference the attached design for layout inspiration.
   - Note: Design may deviate slightly from the main design, akin to the Tumblr app with adjustments.

**2. Intro2 Screen:**
   - Task: Develop the Intro2 screen for additional introductory content.
   - Design: Refer to the attached design, making necessary adjustments for consistency.
   - Note: Minor design alterations allowed for alignment with the app's main design.

**3. Intro3 Screen:**
   - Task: Develop the Intro3 screen for additional introductory content.
   - Design: Refer to the attached design, making necessary adjustments for consistency.
   - Note: Minor design alterations allowed for alignment with the app's main design.

**Happy Contributing!** 🚀

---
Screen one 
![screen1](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/172d0e48-2334-4a8c-b987-ecfef95ca8da)

Screen two 
![screen2](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/ee125cba-4ffb-43e8-8d87-5bcf06b80327)

Screen Th4ree
![screeen3](https://github.com/opencodeiiita/GeekHaven-Community-App/assets/87519281/1c0a184e-a7d7-4e37-9754-50c9b57ea333)

**Comment by criticic** [comment]
claim
