### ISSUE TITLE
Authenticate Me 😢 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/GeekHaven-Community-App#99]
### GitHub Issue: User Registration and Username Screen 📝

**1. User Registration:**
   - Task: Implement code to register users with email and password.
   - Action: Utilize Firebase for user authentication.
   - Note: Password screen is already present; extend functionality to register users.

**2. Username Screen:**
   - Task: Add a new screen for collecting the user's username.
   - Action: Capture and store the username along with email and password in Firebase.
   - Redirect: After registration, smoothly transition users to the HomeActivity.

**Happy Contributing!** 🚀

you have to also give your email id so that you can be added to the firebase console

**Comment by criticic** [comment]
claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by ParadoxNJ005** [comment]
claim
